include: package:flutter_lints/flutter.yaml

linter:
  rules:
    omit_local_variable_types: false
    curly_braces_in_flow_control_structures: false
    always_declare_return_types: true
    prefer_const_constructors: false
