name: Flutter

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Preparing Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Installing dependencies
        run: flutter pub get

      - name: Running lints
        run: flutter analyze

      - name: Running tests with coverage
        run: flutter test --coverage

      - name: Reporting code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 60
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}